### ISSUE TITLE
Does not work in android build - Black screen

### ISSUE THREAD

**Issue by Robb1124** [do-won-kim/Unity_Storage#4]
Any ideas why your fix would not work in an android build in :
URP 12.1.6
Unity 2021.3.0

It produces a black screen. It works as expected in editor. Tried for a long time to make this work without success. It would be game changer for us. Let me know if you have any insights. Thank you for your help !

**Comment by do-won-kim** [comment]
This script is a code based on urp 7.5.1.
I'm surprised that it works in the 12.1.6 editor.
I don't use that function anymore in my project, so it's impossible to check right away.
But I'm interested. I'll upload the code written based on unity 2021 when I have time from next week.

**Comment by do-won-kim** [comment]
> Any ideas why your fix would not work in an android build in : URP 12.1.6 Unity 2021.3.0
> 
> It produces a black screen. It works as expected in editor. Tried for a long time to make this work without success. It would be game changer for us. Let me know if you have any insights. Thank you for your help !

Updated to work with the latest version of Unity 2021. with test apk
